### ISSUE TITLE
What is the StackOverflow database?

### ISSUE THREAD

**Issue by yeguixin** [e32wong/clocom#2]
What‘s the database in the project? In ReadMe you said "The 'database' can be a StackOverflow database". And what's the StackOverflow database? How can I get it? Thanks.

**Comment by e32wong** [comment]
Dataset is available if you send us an email. Check us the website if you need further details.

http://asset.uwaterloo.ca/clocom/

**Comment by e32wong** [comment]
Please check out the README if you would like to download the database. We had added the tar file as a part of the code distribution.

**Comment by yeguixin** [comment]
Got it. Thanks @e32wong
